---
# tasks file for terraform

- name: Install the latest version of Apache
  yum:
    name: yum-utils
    state: latest

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: terraform
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: no
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install the latest version of Apache
  yum:
    name: terraform
    state: latest


#- terraform:
#    project_path: '/etc/ansible/roles/test'
#    force_init: yes
#    plan_file: '/etc/ansible/roles/test/pp.txt'
#    state: planned
#  register: output

- copy:
    src: files/main.tf 
    dest: /etc/ansible/roles/test/
  notify: "terraform apply"

- template:
    src: script/varibles.tf
    dest: /etc/ansible/roles/test/
  notify: "terraform apply"

#- name: terraform apply
#  terraform:
#    force_init: yes
#    project_path: '/etc/ansible/roles/test'
#    state: present
#  register: outputs

#- debug: var=outputs
